### ISSUE TITLE
gfa2view naming issue

### ISSUE THREAD

**Issue by d-ayhan** [codeatcg/VRPG#2]
Hello,
When we run gfa2view with our GFA file, we get the following error message, and our node.info intermediate file looks like below.
We changed segment names to numeric values and followed the PanSN prefix naming pattern for the pathnames but still couldn't fix it.
What do you think would be the issue? And, can you give us an example GFA file to follow?
Thank you.

`../module/gfa2view --GFA input.gfa --ref REF--outDir output_dir --index --range 2000 --thread 3`
`Error: file is empty. output_dir/upload/chr.list`

`#Segment	Chr	Start	End	Len	RefOrNot`
`42043	Un#H#1	1	2200	2200	1`
`42042	Un#H#1	1	9	9	1`
`42041	Un#H#1	1	20	20	1`
`42040	Un#H#1	1	1	1	1`

**Comment by codeatcg** [comment]
It seems that the parameter for option '--ref' is not appropriate (try --ref REF#0).  The haplotype should be specified. Following PanSN prefix naming pattern the path name should be [sample_name + delimiter  + haplotype + delimiter + chromosome_or_contig], e.g. 'HG01071#1#JAHBCF010000010.1'. Sometimes the haplotype assembly is unavailable for a sample. The haplotype name can be omitted, e.g. grch38#chr1.  The parameter for option '--ref' can be set to 'grch38#0'. This is to keep compatible with GFA files created by Minigraph-Cactus and PGGB. There may be some difference between GFA files created by different software.

# truncated GFA by Minigraph-Cactus
H       VN:Z:1.1        RS:Z:SGDref
S       27      TTGAACTCATATGTACCAAGCACC        SN:Z:SGDref#chrIX       SO:i:10390      SR:i:0
S       28      C
S       29      T       SN:Z:SGDref#chrIX       SO:i:10414      SR:i:0
S       30      AAAATTACGCACCCATTTCCATTGGCAAAGACTTG     SN:Z:SGDref#chrIX       SO:i:10415      SR:i:0
S       31      G
S       32      A       SN:Z:SGDref#chrIX       SO:i:10450      SR:i:0
S       33      C       SN:Z:SGDref#chrIX       SO:i:10451      SR:i:0
L       26      +       27      +       0M
L       27      +       28      +       0M
L       27      +       29      +       0M
L       28      +       30      +       0M
L       29      +       30      +       0M
L       30      +       31      +       0M
L       30      +       32      +       0M
L       31      +       33      +       0M
L       32      +       33      +       0M
L       33      +       34      +       0M
L       33      +       35      +       0M
W       SGDref  0       chrIX   0       439888  >26>27>29>30>32>33
W       YPS128  0       chrIX   5942    440914  >27>28>30>31>33
W       YPS606  0       chrIX   6447    448231  >27>28>30>31>33

# truncated GFA by PGGB
H       VN:Z:1.0
S       1       TTTTTGTGTCTCGTCCTCCTC
S       2       ACACCCGCACCGACTGTTAACACC
S       3       CACACACCACACCACACAC
S       4       CC
L       4       +       5       +       0M
S       5       CACACACA
L       5       +       6       +       0M
S       6       CCACA
L       6       +       7       +       0M
L       6       +       8       +       0M
S       7       C
L       7       +       8       +       0M
S       8       CCACACACCACACCCACAC
L       8       +       9       +       0M
L       8       +       10      +       0M
P       Y55#1#chrII     211795+,211796+,211800+,211801+
P       YPS128#1#chrII  211738+,211739+,211740+,211741+,211742+
P       YPS606#1#chrII  211739+,211741+,211743+,211744+,211746+

**Comment by d-ayhan** [comment]
Thank you very much for your quick reply. Our GFA file had problems. After changing the sequence names as shown in the example file we were able to run it.
