### ISSUE TITLE
Bed file upload?

### ISSUE THREAD

**Issue by jelber2** [codeatcg/VRPG#3]
Hi,

This is a very cool tool, so thank you very much. I have so far made a "dual assembly" (http://lh3.github.io/2021/10/10/introducing-dual-assembly)  with Nanopore reads and have made input files with the `vrpg_preprocess.py` script for VRPG. Right now, I have been using Heng Li's minigraph to call SV's such as this example command:

    /home/jelber43/git/minigraph/minigraph -xasm -l10k --call out.gfa ../newAssDir/hg001.1.fa -t 10 > hg001.1.bed

then manually copying and pasting the regions of the BED file above into VRPG.

As a feature request, might it be possible to upload a BED file and be able to scroll through the BED file entries?

**Comment by yjx1217** [comment]
Dear Jean,

Many thanks for the suggestion! And sorry for the belated response! During the past a few months, we have been busy with introducing a feature that enables VRPG to visualize pangenome graph together with genome annotation features, which have been incorporated into the current version of VRPG and its webserver (https://www.evomicslab.org/app/vrpg/). At the same time, we are working on developing a genome graph based SV caller right now, which we hope to introduce to the community soon. Your suggested feature is definitely a nice addition to VRPG and we will try to make it happen in coming months. :-)

Best,
Jia-Xing and Zepu

**Comment by jelber2** [comment]
Thanks!
