### ISSUE TITLE
Issue dealing with .gfa file from minigraph-CACTUS pipeline

### ISSUE THREAD

**Issue by isaacambrogetti** [codeatcg/VRPG#4]
Hello,
I'm having an issue while loading my .gfa file of a pangenome I created using the mingraph-cactus pipeline.   
For context it's a pangenome created from 1 reference + 2 genomes with the following characteristics:
```
nodes   18424540
edges   24616683
length  1069101379
```

I am trying to run the command at the step [Pangenome graph already exists](https://github.com/codeatcg/VRPG?tab=readme-ov-file#pangenome-graph-already-exists), but I do not have the .list files it requires and I cannot find any documentation regarding the minigraph command `-cxasm --vc`.  
I was wondering if you have any suggestion on how to behave when dealing with a file rGFA from the minigraph-cactus pipeline.

Furthermore, I tried to work directly from the step [GFA format graph](https://github.com/codeatcg/VRPG?tab=readme-ov-file#gfa-format-graph) but the `Error: GFA file open failed` araised, which I think it might be due to the fact that I am dealing with a rGFA file and not a GFA.

Thank you in advance!
Isaac

**Comment by codeatcg** [comment]
Thanks for using VRPG and giving feedback. Mingraph-cactus uses GFA 1.1 (https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) , which is different from rGFA (https://github.com/lh3/gfatools/blob/master/doc/rGFA.md). Descriptions of the options '-cxasm --vc' of minigraph can be found by run './minigraph' (without any options) directly from the console. For graph in GFA format created by minigraph-cactus the graph should be converted to a rGFA-like format by gfa2view as described in the document before visualization. The error message 'GFA file open failed' generally means that the file path of GFA file may be incorrect.

**Comment by isaacambrogetti** [comment]
Thank you for answering and for correcting the important misunderstanding I had with the Minigraph-Cactus output.   
My issue was indeed due to an incorrect file path.
